//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adresa()
        {
            this.Korisniks = new HashSet<Korisnik>();
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Zaposleniks = new HashSet<Zaposlenik>();
            this.Zaposleniks1 = new HashSet<Zaposlenik>();
        }
    
        public int IdAdrese { get; set; }
        public string Broj { get; set; }
        public string Ulica { get; set; }
        public string Mjesto { get; set; }
        public string PostanskiBroj { get; set; }
        public string NazivPodruznice { get; set; }
        public string OpisPodruznice { get; set; }
        public Nullable<System.TimeSpan> RadnoVrijemeOd { get; set; }
        public Nullable<System.TimeSpan> RadnoVrijemeDo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korisnik> Korisniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposlenik> Zaposleniks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposlenik> Zaposleniks1 { get; set; }
    }
}
