//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomobilskiDio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AutomobilskiDio()
        {
            this.StavkaRacunaAutomobilskiDios = new HashSet<StavkaRacunaAutomobilskiDio>();
        }
    
        public int IdDijela { get; set; }
        public string Naziv { get; set; }
        public bool Original { get; set; }
        public decimal NabavnaCijena { get; set; }
        public decimal ProdajnaCijena { get; set; }
        public int KolicinaNaSkladistu { get; set; }
        public int Proizvodac { get; set; }
    
        public virtual Proizvodac Proizvodac1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacunaAutomobilskiDio> StavkaRacunaAutomobilskiDios { get; set; }
    }
}
