//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2227_DBEntities1 : DbContext
    {
        public PI2227_DBEntities1()
            : base("name=PI2227_DBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresa> Adresas { get; set; }
        public virtual DbSet<AutomobilskiDio> AutomobilskiDios { get; set; }
        public virtual DbSet<Guma> Gumas { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<MarkaVozila> MarkaVozilas { get; set; }
        public virtual DbSet<NacinPlacanja> NacinPlacanjas { get; set; }
        public virtual DbSet<PranjeVozila> PranjeVozilas { get; set; }
        public virtual DbSet<PrijavaKvara> PrijavaKvaras { get; set; }
        public virtual DbSet<Proizvodac> Proizvodacs { get; set; }
        public virtual DbSet<Racun> Racuns { get; set; }
        public virtual DbSet<Rezervacija> Rezervacijas { get; set; }
        public virtual DbSet<Servi> Servis { get; set; }
        public virtual DbSet<StavkaRacunaAutomobilskiDio> StavkaRacunaAutomobilskiDios { get; set; }
        public virtual DbSet<StavkaRacunaGuma> StavkaRacunaGumas { get; set; }
        public virtual DbSet<StavkaRacunaVozilo> StavkaRacunaVoziloes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TestVoznja> TestVoznjas { get; set; }
        public virtual DbSet<UlogaKorisnika> UlogaKorisnikas { get; set; }
        public virtual DbSet<Vozilo> Voziloes { get; set; }
        public virtual DbSet<VrstaGoriva> VrstaGorivas { get; set; }
        public virtual DbSet<VrstaVozila> VrstaVozilas { get; set; }
        public virtual DbSet<Zaposlenik> Zaposleniks { get; set; }
    }
}
