//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.StavkaRacunaAutomobilskiDios = new HashSet<StavkaRacunaAutomobilskiDio>();
            this.StavkaRacunaGumas = new HashSet<StavkaRacunaGuma>();
            this.StavkaRacunaVoziloes = new HashSet<StavkaRacunaVozilo>();
        }
    
        public int IdRacuna { get; set; }
        public System.DateTime DatumIVrijeme { get; set; }
        public int Zaposlenik { get; set; }
        public string Opis { get; set; }
        public decimal Iznos { get; set; }
        public int Korisnik { get; set; }
        public Nullable<int> Servis { get; set; }
        public int NacinPlacanja { get; set; }
    
        public virtual Korisnik Korisnik1 { get; set; }
        public virtual NacinPlacanja NacinPlacanja1 { get; set; }
        public virtual Servis Servi { get; set; }
        public virtual Zaposlenik Zaposlenik1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacunaAutomobilskiDio> StavkaRacunaAutomobilskiDios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacunaGuma> StavkaRacunaGumas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacunaVozilo> StavkaRacunaVoziloes { get; set; }
    }
}
