//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servi()
        {
            this.Racuns = new HashSet<Racun>();
        }
    
        public int IdServisa { get; set; }
        public string Opis { get; set; }
        public System.DateTime DatumIVrijeme { get; set; }
        public int SatiRada { get; set; }
        public decimal CijenaSatnice { get; set; }
        public int Zaposlenik { get; set; }
        public int Vozilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Racun> Racuns { get; set; }
        public virtual Vozilo Vozilo1 { get; set; }
        public virtual Zaposlenik Zaposlenik1 { get; set; }
    }
}
