//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class StavkaRacunaVozilo
    {
        public int Vozilo { get; set; }
        public int Racun { get; set; }
        public int Kolicina { get; set; }
        public decimal Cijena { get; set; }
    
        public virtual Racun Racun1 { get; set; }
        public virtual Vozilo Vozilo1 { get; set; }
    }
}
