//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI_Projekt_Autokuca.Baza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.PranjeVozilas = new HashSet<PranjeVozila>();
            this.PrijavaKvaras = new HashSet<PrijavaKvara>();
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Servis = new HashSet<Servis>();
            this.StavkaRacunaVoziloes = new HashSet<StavkaRacunaVozilo>();
            this.TestVoznjas = new HashSet<TestVoznja>();
        }
    
        public int IdVozila { get; set; }
        public string RegistraskaOznaka { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Cijena { get; set; }
        public Nullable<int> GodineJamstva { get; set; }
        public int GodinaProizvodnje { get; set; }
        public int SnagaMotora { get; set; }
        public int StupanjMjenjaca { get; set; }
        public string Boja { get; set; }
        public int BrojPrijedenihKilometara { get; set; }
        public int Marka { get; set; }
        public int Vlasnik { get; set; }
        public int Vrsta { get; set; }
        public int Gorivo { get; set; }
        public byte[] Fotografija { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual MarkaVozila MarkaVozila { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PranjeVozila> PranjeVozilas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrijavaKvara> PrijavaKvaras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkaRacunaVozilo> StavkaRacunaVoziloes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestVoznja> TestVoznjas { get; set; }
        public virtual VrstaGoriva VrstaGoriva { get; set; }
        public virtual VrstaVozila VrstaVozila { get; set; }
    }
}
